#!/usr/bin/env node
// D-1133-07: Dependency graph visualization — pattern→fix chain — Epic #1133
'use strict';
const fs=require('fs'),path=require('path');

const PATTERNS_FILE=path.join(__dirname,'../..','instructions','recurring-patterns.json');
const INCIDENTS_FILE=path.join(process.env.HOME,'.megingjord','incidents.jsonl');
const OUT_FILE=path.join(__dirname,'../..','research','anneal-pattern-graph.md');

function loadPatterns(){
  try{return JSON.parse(fs.readFileSync(PATTERNS_FILE,'utf8')).patterns||[];}
  catch(e){console.error(`❌ patterns: ${e.message}`);return[];}
}

function loadCoOccurrence(){
  const co={};
  if(!fs.existsSync(INCIDENTS_FILE))return co;
  const byDay={};
  fs.readFileSync(INCIDENTS_FILE,'utf8').split('\n').filter(l=>l)
    .forEach(l=>{try{const i=JSON.parse(l);
      const day=i.timestamp.slice(0,10);
      if(!byDay[day])byDay[day]=[];
      byDay[day].push(i.pattern_id);}catch(e){}});
  for(const day of Object.values(byDay)){
    for(let a=0;a<day.length;a++){for(let b=a+1;b<day.length;b++){
      const k=`${day[a]}->${day[b]}`;co[k]=(co[k]||0)+1;
    }}
  }
  return co;
}

function sanitize(s){return s.replace(/[^a-zA-Z0-9_]/g,'_').slice(0,40);}

function buildGraph(patterns,co){
  const lines=['graph TD'];
  for(const p of patterns){
    const id=sanitize(p.id);
    const label=p.name.replace(/"/g,"'").slice(0,35);
    const refs=(p.related_tickets||[]).join(', ');
    lines.push(`  ${id}["${label}${refs?' '+refs:''}"]`);
  }
  for(const [edge,count] of Object.entries(co)){
    if(count<1)continue;
    const [a,b]=edge.split('->').map(sanitize);
    lines.push(`  ${a} -->|co:${count}| ${b}`);
  }
  return lines.join('\n');
}

function main(){
  const patterns=loadPatterns();
  if(!patterns.length){console.error('❌ No patterns loaded');process.exit(1);}
  const co=loadCoOccurrence();
  const mermaid=buildGraph(patterns,co);
  const date=new Date().toISOString().slice(0,10);
  const md=[
    `# Anneal Pattern Graph — ${date}`,
    '',
    `> Auto-generated by \`scripts/global/anneal-graph.js\` — Epic #1133`,
    `> Nodes = recurring patterns | Edges = co-occurrence in incidents.jsonl`,
    '',
    '```mermaid',
    mermaid,
    '```',
    '',
    `## Pattern Inventory (${patterns.length} total)`,
    '',
    ...patterns.map(p=>`- **${p.id}**: ${p.name} — \`${p.proposed_remediation}\``)
  ].join('\n');
  fs.writeFileSync(OUT_FILE,md+'\n');
  console.log(`✅ Graph written to research/anneal-pattern-graph.md (${patterns.length} patterns, ${Object.keys(co).length} co-edges)`);
}

main();
