version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "chf3198"
    labels:
      - "priority:p2"
    open-pull-requests-limit: 5
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "chf3198"
    labels:
      - "priority:p2"
    open-pull-requests-limit: 5
