// Help User Sections — task-oriented help for dashboard operators

const HELP_USER_SECTIONS = [
  { id: 'start-what', title: '🚀 What is DevEnv Ops?',
    body: 'DevEnv Ops is a fleet operations dashboard for monitoring devices, AI services, and Agile agent workflows. The <strong>Fleet view</strong> shows the baton pipeline, health log, activity feed, and context flow. <strong>Ops</strong> shows quotas, router, governance, and ticket log. <strong>Resources</strong> has device/service cards. <strong>Wiki</strong> is the research browser. Every panel has a <strong>? button</strong> for context-sensitive help.' },
  { id: 'start-tour', title: '🗺️ Dashboard tour',
    body: '<strong>Nav bar</strong>: 🔴 Live · 📜 Logs · 📊 Ops · 🌐 Fleet · 📚 Wiki · 📘 Help. <strong>Header buttons</strong>: ↻ refresh now · ⏱️ toggle auto-refresh · 🧪 stress test · 💡 toggle tooltips · ◐ high contrast. <strong>Each panel h2</strong> has a <strong>? button</strong> — click or hover for panel-specific help when tooltips are on.' },
  { id: 'use-baton', title: '🔄 Agent Baton — reading ticket pipelines',
    body: 'The Agent Baton panel shows every <em>active</em> ticket as a row. <strong>Role pipeline</strong>: 🎯 Mgr → 🔧 Collab → ⚙️ Admin → 🔍 Review. Highlighted blue = current role. Green border = completed. <strong>Baton history</strong> (bottom of each row): chained icons + timestamps = each time the baton changed hands. Hover a step for role description and time. <strong>Closed tickets</strong> (done/cancelled) move to Ticket Log in Ops view.' },
  { id: 'use-health', title: '💚 Fleet Health Log',
    body: 'Timestamped log of device health events. Each entry shows device name, status change (online/offline/degraded), latency, and timestamp. <strong>Green</strong> = healthy · <strong>Yellow</strong> = degraded · <strong>Red</strong> = offline. The ⭐ icon marks the primary dev workstation; ⚡ = OpenClaw proxy; 🤖 = Ollama inference node.' },
  { id: 'use-context', title: '🧠 Context Flow diagram',
    body: 'Shows how prompts are routed: <strong>VS Code Copilot Agent</strong> → <strong>AUTO router</strong> → Cloud LLM (Copilot API) or OpenClaw (LiteLLM proxy) → Ollama (local models). Solid arrows = primary paths; dashed = local/fallback routes. This replaced the old Fleet Topology panel.' },
  { id: 'use-activity', title: '📡 Live Activity feed',
    body: 'Timestamped event stream. Event types: 🎫 ticket created · 🏷️ role/baton events · 🌿 branch ops · 🔀 PRs · ✅ merges · 🚀 deploys · 🧪 test runs. Newest on top, max 30 entries. Click ↻ to force a poll.' },
  { id: 'use-quotas', title: '📊 Quotas & LLM Context Windows',
    body: 'Quotas shows daily API usage bars per model — red = near limit, resets midnight UTC. LLM Context Windows shows live token usage: prompt tokens + completion tokens / total context window. High fill % = approaching truncation risk.' },
  { id: 'use-router', title: '🛣️ Task Router & LLM Log',
    body: 'Task Router Lanes shows how tasks are distributed across Free (local/Ollama), Fleet (OpenClaw), and Premium (cloud) lanes. LLM Router Log shows per-request model selection decisions with agent name, model chosen, and task snippet.' },
  { id: 'use-governance', title: '🛡️ Governance & Ticket Log',
    body: 'Governance panel flags baton protocol violations: skipped roles, missing handoff artifacts, ACs without evidence. Ticket Log is the full audit trail — all statuses including done and cancelled. Active tickets shown first; closed collapse into a details group.' },
  { id: 'use-stress', title: '🧪 Stress test',
    body: 'Click 🧪 to run a 60s simulation: 5 parallel mock tickets through all 4 roles, mock router log entries, device status cycling. Exercises every panel. Safe to run at any time — mock data only, no real API calls.' },
  { id: 'trouble-offline', title: '🔴 Device shows as offline',
    body: '<strong>Causes</strong>: Device off · Tailscale disconnected · health check timeout (2.5s). <strong>Fix</strong>: Check power → verify <code>tailscale status</code> on device → click ↻.' },
  { id: 'trouble-stale', title: '⏳ Data appears stale',
    body: '<strong>Causes</strong>: Auto-refresh disabled · browser tab backgrounded · network error. <strong>Fix</strong>: Click ↻ → check ⏱️ is active → verify network.' },
  { id: 'use-github', title: '🐙 GitHub Activity',
    body: 'Recent commits, PRs, and issues from the devenv-ops repo. Each row shows event type, title, author, and relative time. Click a row to open on GitHub.' },
  { id: 'use-ticket-log', title: '📋 Ticket Log',
    body: 'Full audit trail of all tickets. Active tickets shown first with current status. Closed/cancelled tickets collapse into a details group. Each entry shows ticket #, title, status, and last update.' },
  { id: 'use-devices', title: '🏗️ Fleet Devices',
    body: 'Device inventory cards: name, Tailscale IP, RAM, OS, role (primary/proxy/inference). Green border = online. Red = offline. ⭐ = primary dev · ⚡ = OpenClaw proxy · 🤖 = Ollama node.' },
  { id: 'use-services', title: '⚡ Services',
    body: 'API service status cards: endpoint URL, current status (healthy/degraded/down), last check timestamp. Services include Ollama, LiteLLM, Tailscale, and GitHub API.' },
  { id: 'use-settings', title: '⚙️ Fleet Resources',
    body: 'LLM credential store and health probes. Shows configured API keys (masked), endpoint URLs, and probe results. Edit credentials via form, changes persist to localStorage.' },
  { id: 'use-config', title: '⚙️ Dashboard Config',
    body: 'Dashboard preferences: auto-refresh interval, high-contrast toggle, tooltip enable/disable. Changes apply immediately and persist to localStorage.' },
  { id: 'use-wiki-metrics', title: '📊 Wiki Metrics',
    body: 'Research wiki statistics: total pages, coverage %, average staleness, most/least accessed. Helps identify gaps and stale content in the research archive.' },
  { id: 'use-wiki-reader', title: '📚 Wiki Reader',
    body: 'Browse and search research/ markdown pages inline. Click a page title to expand its rendered content. Search filters by title and body text.' },
];
